### ISSUE TITLE
Implement the user interface flow

### ISSUE THREAD

**Issue by santiago-rodrig** [santiago-rodrig/tic_tac_toe#3]
### No dummy content

There is not a dummy user interface to see the overall behavior of the tic tac toe game, please implement that.

**Comment by santiago-rodrig** [comment]
We're implementing it right now. Here is a [link to the pull request](https://github.com/santiago-rodrig/tic_tac_toe/pull/6).

**Comment by mohamednaser** [comment]
the feature developed and merged with develop branch
